### ISSUE TITLE
[CRITICAL] QNetworkReplyImpl: backend error: caching was enabled after some bytes had been written

### ISSUE THREAD

**Issue by suroorwijdan** [peerigon/phridge#23]
I am trying to spawn multiple child phantom processes using `phridge` which perform certain tasks like submitting form. 

Everything works fine when the number of processes is less then `8` but as soon as i try to spawn `8` or more then `8` `phridge` process i get the below error. 

```
2014-11-26T14:41:31 [CRITICAL] QNetworkReplyImpl: backend error: caching was enabled after some bytes had been written
2014-11-26T14:41:31 [CRITICAL] QNetworkReplyImpl: backend error: caching was enabled after some bytes had been written
```

Is it something related to PhantomJS itself, i am using the latest build of `PhantomJS 2`. ?

**Comment by pilavdzic** [comment]
This is definitely a phantomjs 2 bug nothing to do with phridge, as I am getting this error while using casperjs on windows with no nodejs.

Having same problem though, can you post link to the phantomjs 2 bug so I can comment there... Having trouble finding it.
