### ISSUE TITLE
Trying to page.open, but no joy

### ISSUE THREAD

**Issue by paulxtiseo** [peerigon/phridge#24]
Using phridge to run Phantom to login into a site and retrieve an attachment. This is done inside the SailsJS framework.

Running
```
sails.phridge
  .spawn()          
  .then(function(phantom) { 
    
    return phantom.run(function() {  
      console.log('run');
      page = webpage.create();
      page.open('https://commercialservices.freshservice.com/support/login', function(status) {
        console.log('hi');
        page.render('test.png');
      });
      console.log('run');
    });

  })
  .catch(function(e) {
    sails.log.info('catch');
    sails.log.error(e);
  })
  .finally(function(f) {
    sails.log.info('finally');
    sails.log.info(f);
  });
```
does not result in a console.log() or a page.render() inside the page.open(). However, I do see the two console.log('run') lines output to the screen. Running the same block of code inside page.open() directly in PhantomJS does produce a PNG. Am I doing something wrong?

PS: FWIW, the `sails.phridge...` line is equivalent to a `require('phridge')`

**Comment by jhnns** [comment]
Close?

**Comment by paulxtiseo** [comment]
Yes. I have moved on to another approach, and so if I somehow circle back to this, I'll reopen or create a new ticket. Sorry for the inconvenience.

**Comment by jhnns** [comment]
No worries. :+1:
