### ISSUE TITLE
Create a page by passing static html and render it

### ISSUE THREAD

**Issue by marto83** [peerigon/phridge#25]
phridge looks great. I have a couple of questions. 

Is it possible to create a page by passing an html string instead of url?

How can I tell the phantom process to render the page to base64?

**Comment by jhnns** [comment]
Phridge is just a bridge between node and PhantomJS. For PhantomJS-related questions, please [read the docs](http://phantomjs.org/documentation/), [ask on Stackoverflow](http://stackoverflow.com/questions/tagged/phantomjs) or [create an issue at their repo](https://github.com/ariya/phantomjs).

Some hints for your questions:

> Is it possible to create a page by passing an html string instead of url?

Your probably looking for [`page.setContent`](http://phantomjs.org/api/webpage/method/set-content.html)

> How can I tell the phantom process to render the page to base64?

[`page.renderBase64`](http://phantomjs.org/api/webpage/method/render-base64.html)
