### ISSUE TITLE
Wrong PhantomJS binary?

### ISSUE THREAD

**Issue by MiroHibler** [peerigon/phridge#38]
I'm having an issue with PhantomJS on Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-57-generic x86_64) throwing this error (used in [UnCSS](https://github.com/giakki/uncss) package):

```shell
<snip>/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string
```

When I try to invoke it manually from the same path, I get:

```shell
./phantomjs: cannot execute binary file: Exec format error
```

it seems that the included phantomjs package installs wrong binary for this architecture.

**Comment by jhnns** [comment]
Please report this issue to the npm package [phantomjs](https://github.com/Medium/phantomjs) which is responsible for downloading the correct binary.
