### ISSUE TITLE
Cannot read property 'stdin' of null

### ISSUE THREAD

**Issue by w0rm** [peerigon/phridge#41]
Hello! Thanks for this wonderful wrapper that makes interaction with phantom much simpler and straightforward.

I am using phridge to generate png sprite from svg sources. Yesterday I received an issue from someone using my gulp plugin: https://github.com/w0rm/gulp-svgfallback/issues/7 with an error message coming from phridge sources.

I am not able to reproduce this, but, maybe, you have an idea of what can possibly go wrong there.

phridge is used only in the `generateSprite` function: https://github.com/w0rm/gulp-svgfallback/blob/master/index.js#L104

**Comment by jhnns** [comment]
Thx for reporting this, I'll take a look :grin:

**Comment by w0rm** [comment]
@jhnns thanks for helping out!

**Comment by ChrisZieba** [comment]
@jhnns was there ever a fix for this? I'm seeing this happen quite a bit on our end. Any info you need to help resolve? 

```
TypeError: Cannot read property 'stdin' of null
    at Phantom._write (/var/app/current/node_modules/phridge/lib/Phantom.js:229:43)
    at /var/app/current/node_modules/phridge/lib/Phantom.js:217:14
    at new wrappedPromise (/var/app/current/node_modules/newrelic/lib/instrumentation/core/globals.js:133:18)
    at Phantom._send (/var/app/current/node_modules/phridge/lib/Phantom.js:201:12)
    at Page.run (/var/app/current/node_modules/phridge/lib/Page.js:60:25)
    at Object.server.checkIfPageIsDoneLoading (/var/app/current/node_modules/prerender/lib/server.js:289:24)
    at Timeout._repeat (/var/app/current/node_modules/prerender/lib/server.js:251:19)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I temporarily modified our module to return if not defined

```js
Phantom.prototype._write = function (message) {
    if (!this.childProcess || !this.childProcess.stdin) return;
    this.childProcess.stdin.write(JSON.stringify(message) + os.EOL, "utf8");
};
```

**Comment by jhnns** [comment]
We could add this `if` clause, but that would just obscure the underlying problem. This callback should never been called when `childProcess` is `null` so we have to find that cause first.

Can you give some additional information? When exactly does that error happen? Can you reproduce it reliably?

**Comment by ChrisZieba** [comment]
Havent been able to reproduce since updating prerender. Might have been caused by this: https://github.com/prerender/prerender/issues/342#issuecomment-242588130

**Comment by jhnns** [comment]
Ok. I'll re-open it when you have more information :)

**Comment by Kakise** [comment]
I've got the same error on my end quite a bit. I don't know how to solve it.

https://github.com/Kakise/Blog/issues/24

If you check the travis build logs, you'll see that it is a completely random issue.
