### ISSUE TITLE
Memory exhausted?

### ISSUE THREAD

**Issue by moshewe** [peerigon/phridge#52]
I got the following error:
```
Memory exhausted.
c:\Exposebox\Source\Spider\node_modules\phridge\lib\Phantom.js:380
        error.message = errorMessage + ": " + error.message;
                      ^

TypeError: Cannot assign to read only property 'message' of 1
    at Phantom._onUnexpectedError (c:\Exposebox\Source\Spider\node_modules\phridge\lib\Phantom.js:380:23)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
From I can understand, this means that the phantom process exited with status `1`?

**Comment by jhnns** [comment]
Hi. It looks like your either your Node.js or Phantom process takes up too much memory. There's nothing phridge could do about it :)

I'll reopen this issue when you add an example that this is an issue with phridge itself.

**Comment by zhukevgeniy** [comment]
Hi, @jhnns . I have the same problem. And I can't fixed it. What's wrong with this [code](https://gitlab.com/evgeniy.zhuk/node-phantomjs-web-scraper/blob/master/phridge-parser.js) ?

**Comment by zhukevgeniy** [comment]
Hi, @jhnns . I have the same problem I can't resolve. Can u help me, what's wrong with this [code](https://gitlab.com/evgeniy.zhuk/node-phantomjs-web-scraper/blob/master/phridge-parser.js)?

**Comment by jhnns** [comment]
Why do you set `process.setMaxListeners(Infinity);`?

The code looks fine, although you could re-use the phantom process. A single phantomjs process can open multiple pages.

**Comment by zhukevgeniy** [comment]
Thanx for advise, @jhnns , but how can I solve this issue? I mean `memory exhausted`.

**Comment by zhukevgeniy** [comment]
And can I iterate over 3,4k+ urls in one process?

**Comment by jhnns** [comment]
What kind of answer to you expect from me? I know nothing about your setup.

Besides that, the error is pretty clear: Memory exhausted. There is something that takes up too much memory. Phridge is just a bridge to PhantomJS, your error is not related to Phridge itself (unless you can show me that Phridge is eating up too much memory).

**Comment by a-bobkov** [comment]
@zhukevgeniy As far as I tried, it's not possible to open 3,4k+ urls in one PhantomJS process. Probably due to some memory leaks in PhantomJS. But you can open many PhantomJS processes consequently, killing the previous process, of course. That way I opened 6K+ urls someday.
